"""add destination area

Revision ID: 0a264dfca4d4
Revises: b1aa4b815054
Create Date: 2025-03-09 20:37:13.810369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a264dfca4d4'
down_revision: Union[str, None] = 'b1aa4b815054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('destination_area', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'destination_area')
    # ### end Alembic commands ###
